{
  "hash": "d5fa8fc4bbe201f2fdd2d7e4415f1476",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 1: Survey Analysis with Data Visualisation\"\nauthor: \"Guofang Ji\"\nformat:\n  html:\n    theme: cosmo\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\n---\n\n## Introduction\n\nThis report uses the dataset **\"Income of informal labourers in rural areas: A survey dataset of northern mountainous regions in Vietnam\"** (Mai et al., *Data in Brief* 38, 2021). Survey analysis transforms raw survey data into decision-relevant insights by identifying patterns, trends, and relationships using descriptive and visual methods. The analysis below applies **tidyverse** and **ggplot2** to load, prepare, and visualise the data.\n\n::: callout-note\n## Data source\n\nRaw data: spreadsheet (725 rows × 29 columns) from Mendeley Data, stored in the project `data/` folder.\n\n**Link**: <https://data.mendeley.com/datasets/s6p7dwj3j6/1> (DOI: 10.17632/s6p7dwj3j6.1)\n:::\n\n## Data and methods\n\n### Packages and data import\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(tidyverse, patchwork, scales, readxl, viridis, ggstatsplot, DT)\n```\n:::\n\n\n*Upload for elsiver.xlsx* is read with **readxl**’s [`read_excel()`](https://readxl.tidyverse.org/reference/read_excel.html). Categorical columns are converted to character; then **recode** is used so that every chart shows meaningful labels instead of numeric codes (Mai et al. 2021, Table 1).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Province codes 1--5: Tuyen Quang, Quang Ninh, Ha Giang, Yen Bai, Bac Giang (Mai et al. 2021)\nsurvey <- read_excel(\"data/Upload for elsiver.xlsx\") %>%\n  mutate(across(where(is.character), ~ na_if(., \"\"))) %>%\n  mutate(across(any_of(c(\"CPRO\", \"CGEN\", \"CRAC\", \"CJOB\", \"CQUI\", \"FEDU\", \"FVTP\", \"FCRA\", \"FTAP\")), as.character)) %>%\n  filter(is.finite(TEIN)) %>%\n  mutate(\n    CGEN = factor(CGEN, levels = c(\"1\", \"2\"), labels = c(\"Male\", \"Female\")),\n    CPRO = recode(CPRO,\n                  \"1\" = \"Tuyen Quang\", \"2\" = \"Quang Ninh\", \"3\" = \"Ha Giang\",\n                  \"4\" = \"Yen Bai\", \"5\" = \"Bac Giang\"),\n    FEDU_label = recode(as.character(FEDU),\n                        \"0\" = \"No formal\", \"1\" = \"Primary\", \"2\" = \"Secondary\",\n                        \"3\" = \"Higher\", .default = NA_character_),\n    FCRA = recode(as.character(FCRA),\n                  \"1\" = \"Low\", \"2\" = \"Medium\", .default = NA_character_),\n    FCRA = fct_relevel(factor(FCRA), \"Low\", \"Medium\"),\n    CRAC = factor(recode(as.character(CRAC),\n                        \"1\" = \"Kinh\", \"2\" = \"Ethnic minority\", .default = NA_character_),\n                  levels = c(\"Kinh\", \"Ethnic minority\"))\n  )\nsurvey\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 724 × 31\n   CPRO  CGEN  CRAC  CJOB  CQUI   TEIN  TAIN  TSII  TOIN FEDU  FVTP  FCRA  FTAP \n   <chr> <fct> <fct> <chr> <chr> <dbl> <dbl> <dbl> <dbl> <chr> <chr> <fct> <chr>\n 1 Tuye… Male  Ethn… 1     3        37    25     7     5 1     1     Low   1    \n 2 Tuye… Male  Ethn… 1     5        25    22     0     3 0     1     Medi… 1    \n 3 Tuye… Fema… Ethn… 3     3        33    25     0     8 1     1     Low   2    \n 4 Tuye… Male  Ethn… 1     3        35    30     5     0 1     1     Low   <NA> \n 5 Tuye… Fema… Ethn… 1     3        36    28     0     8 0     1     Low   2    \n 6 Tuye… Fema… Ethn… <NA>  4        21    17     0     4 0     1     Low   2    \n 7 Tuye… Male  Ethn… 3     1        35    25     0    10 3     2     Low   2    \n 8 Tuye… Male  Ethn… 1     3        36    28     0     8 0     1     Low   2    \n 9 Tuye… Male  Ethn… 3     3        38    26    12     0 2     2     Low   2    \n10 Tuye… Male  Ethn… 1     3        30    22     2     6 0     1     Low   2    \n# ℹ 714 more rows\n# ℹ 18 more variables: LHO1 <dbl>, LHO2 <dbl>, LHO3 <dbl>, LHO4 <dbl>,\n#   LCRE <dbl>, LSAV <dbl>, LWDA <dbl>, PPO1 <dbl>, PPO2 <dbl>, PPO3 <dbl>,\n#   PPO4 <dbl>, PPO5 <dbl>, ARO1 <dbl>, ARO2 <dbl>, ARO3 <dbl>, ARO4 <chr>,\n#   ARO5 <dbl>, FEDU_label <chr>\n```\n\n\n:::\n:::\n\n\nOne row with missing or non-finite total income (TEIN) is excluded; the analytic sample has 724 rows and 29 columns. Variables used (see Mai et al. 2021, Table 1 for the full codebook):\n\n-   **Characteristics**: CPRO (province), CGEN (gender), CRAC (race), CJOB (career), CQUI (income quintile).\n-   **Income** (Mil VND): TEIN (total income), TAIN (agricultural), TSII (service and industrial), TOIN (others).\n-   **Factors**: FEDU (education), FVTP (vocational training), FCRA (credit accessibility), FTAP (technological application). FCRA has two levels in this dataset (Low / Medium; Mai et al. 2021, Table 1); CRAC (race) is mapped to Kinh / Ethnic minority. All categorical variables use readable labels; FCRA is ordered Low → Medium.\n\n**Data preview** (searchable, sortable table):\n\n\n::: {#tbl-preview .cell tbl-cap='Survey data preview (724 rows)'}\n\n```{.r .cell-code}\nDT::datatable(survey, filter = \"top\", options = list(pageLength = 10))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-740e0539bba28729a12c\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-740e0539bba28729a12c\">{\"x\":{\"filter\":\"top\",\"vertical\":false,\"filterHTML\":\"<tr>\\n  <td><\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"factor\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"width: 100%; display: none;\\\">\\n      <select multiple=\\\"multiple\\\" style=\\\"width: 100%;\\\" data-options=\\\"[&quot;Male&quot;,&quot;Female&quot;]\\\"><\\/select>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"factor\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"width: 100%; display: none;\\\">\\n      <select multiple=\\\"multiple\\\" style=\\\"width: 100%;\\\" data-options=\\\"[&quot;Kinh&quot;,&quot;Ethnic minority&quot;]\\\"><\\/select>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"560\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"340\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"100\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"-6\\\" data-max=\\\"180\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"factor\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"width: 100%; display: none;\\\">\\n      <select multiple=\\\"multiple\\\" style=\\\"width: 100%;\\\" data-options=\\\"[&quot;Low&quot;,&quot;Medium&quot;]\\\"><\\/select>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\" disabled=\\\"\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"1\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\" disabled=\\\"\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"1\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\" disabled=\\\"\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"1\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\" disabled=\\\"\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"1\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"600\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"5000\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"500\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"5\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"0\\\" data-max=\\\"5\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"1\\\" data-max=\\\"5\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"1\\\" data-max=\\\"3\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"1\\\" data-max=\\\"3\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"1\\\" data-max=\\\"3\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"1\\\" data-max=\\\"11\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"1\\\" data-max=\\\"3\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"number\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n    <div style=\\\"display: none;position: absolute;width: 200px;opacity: 1\\\">\\n      <div data-min=\\\"1\\\" data-max=\\\"3\\\"><\\/div>\\n      <span style=\\\"float: left;\\\"><\\/span>\\n      <span style=\\\"float: right;\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n  <td data-type=\\\"character\\\" style=\\\"vertical-align: top;\\\">\\n    <div class=\\\"form-group has-feedback\\\" style=\\\"margin-bottom: auto;\\\">\\n      <input type=\\\"search\\\" placeholder=\\\"All\\\" class=\\\"form-control\\\" style=\\\"width: 100%;\\\"/>\\n      <span class=\\\"glyphicon glyphicon-remove-circle form-control-feedback\\\"><\\/span>\\n    <\\/div>\\n  <\\/td>\\n<\\/tr>\",\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\",\"179\",\"180\",\"181\",\"182\",\"183\",\"184\",\"185\",\"186\",\"187\",\"188\",\"189\",\"190\",\"191\",\"192\",\"193\",\"194\",\"195\",\"196\",\"197\",\"198\",\"199\",\"200\",\"201\",\"202\",\"203\",\"204\",\"205\",\"206\",\"207\",\"208\",\"209\",\"210\",\"211\",\"212\",\"213\",\"214\",\"215\",\"216\",\"217\",\"218\",\"219\",\"220\",\"221\",\"222\",\"223\",\"224\",\"225\",\"226\",\"227\",\"228\",\"229\",\"230\",\"231\",\"232\",\"233\",\"234\",\"235\",\"236\",\"237\",\"238\",\"239\",\"240\",\"241\",\"242\",\"243\",\"244\",\"245\",\"246\",\"247\",\"248\",\"249\",\"250\",\"251\",\"252\",\"253\",\"254\",\"255\",\"256\",\"257\",\"258\",\"259\",\"260\",\"261\",\"262\",\"263\",\"264\",\"265\",\"266\",\"267\",\"268\",\"269\",\"270\",\"271\",\"272\",\"273\",\"274\",\"275\",\"276\",\"277\",\"278\",\"279\",\"280\",\"281\",\"282\",\"283\",\"284\",\"285\",\"286\",\"287\",\"288\",\"289\",\"290\",\"291\",\"292\",\"293\",\"294\",\"295\",\"296\",\"297\",\"298\",\"299\",\"300\",\"301\",\"302\",\"303\",\"304\",\"305\",\"306\",\"307\",\"308\",\"309\",\"310\",\"311\",\"312\",\"313\",\"314\",\"315\",\"316\",\"317\",\"318\",\"319\",\"320\",\"321\",\"322\",\"323\",\"324\",\"325\",\"326\",\"327\",\"328\",\"329\",\"330\",\"331\",\"332\",\"333\",\"334\",\"335\",\"336\",\"337\",\"338\",\"339\",\"340\",\"341\",\"342\",\"343\",\"344\",\"345\",\"346\",\"347\",\"348\",\"349\",\"350\",\"351\",\"352\",\"353\",\"354\",\"355\",\"356\",\"357\",\"358\",\"359\",\"360\",\"361\",\"362\",\"363\",\"364\",\"365\",\"366\",\"367\",\"368\",\"369\",\"370\",\"371\",\"372\",\"373\",\"374\",\"375\",\"376\",\"377\",\"378\",\"379\",\"380\",\"381\",\"382\",\"383\",\"384\",\"385\",\"386\",\"387\",\"388\",\"389\",\"390\",\"391\",\"392\",\"393\",\"394\",\"395\",\"396\",\"397\",\"398\",\"399\",\"400\",\"401\",\"402\",\"403\",\"404\",\"405\",\"406\",\"407\",\"408\",\"409\",\"410\",\"411\",\"412\",\"413\",\"414\",\"415\",\"416\",\"417\",\"418\",\"419\",\"420\",\"421\",\"422\",\"423\",\"424\",\"425\",\"426\",\"427\",\"428\",\"429\",\"430\",\"431\",\"432\",\"433\",\"434\",\"435\",\"436\",\"437\",\"438\",\"439\",\"440\",\"441\",\"442\",\"443\",\"444\",\"445\",\"446\",\"447\",\"448\",\"449\",\"450\",\"451\",\"452\",\"453\",\"454\",\"455\",\"456\",\"457\",\"458\",\"459\",\"460\",\"461\",\"462\",\"463\",\"464\",\"465\",\"466\",\"467\",\"468\",\"469\",\"470\",\"471\",\"472\",\"473\",\"474\",\"475\",\"476\",\"477\",\"478\",\"479\",\"480\",\"481\",\"482\",\"483\",\"484\",\"485\",\"486\",\"487\",\"488\",\"489\",\"490\",\"491\",\"492\",\"493\",\"494\",\"495\",\"496\",\"497\",\"498\",\"499\",\"500\",\"501\",\"502\",\"503\",\"504\",\"505\",\"506\",\"507\",\"508\",\"509\",\"510\",\"511\",\"512\",\"513\",\"514\",\"515\",\"516\",\"517\",\"518\",\"519\",\"520\",\"521\",\"522\",\"523\",\"524\",\"525\",\"526\",\"527\",\"528\",\"529\",\"530\",\"531\",\"532\",\"533\",\"534\",\"535\",\"536\",\"537\",\"538\",\"539\",\"540\",\"541\",\"542\",\"543\",\"544\",\"545\",\"546\",\"547\",\"548\",\"549\",\"550\",\"551\",\"552\",\"553\",\"554\",\"555\",\"556\",\"557\",\"558\",\"559\",\"560\",\"561\",\"562\",\"563\",\"564\",\"565\",\"566\",\"567\",\"568\",\"569\",\"570\",\"571\",\"572\",\"573\",\"574\",\"575\",\"576\",\"577\",\"578\",\"579\",\"580\",\"581\",\"582\",\"583\",\"584\",\"585\",\"586\",\"587\",\"588\",\"589\",\"590\",\"591\",\"592\",\"593\",\"594\",\"595\",\"596\",\"597\",\"598\",\"599\",\"600\",\"601\",\"602\",\"603\",\"604\",\"605\",\"606\",\"607\",\"608\",\"609\",\"610\",\"611\",\"612\",\"613\",\"614\",\"615\",\"616\",\"617\",\"618\",\"619\",\"620\",\"621\",\"622\",\"623\",\"624\",\"625\",\"626\",\"627\",\"628\",\"629\",\"630\",\"631\",\"632\",\"633\",\"634\",\"635\",\"636\",\"637\",\"638\",\"639\",\"640\",\"641\",\"642\",\"643\",\"644\",\"645\",\"646\",\"647\",\"648\",\"649\",\"650\",\"651\",\"652\",\"653\",\"654\",\"655\",\"656\",\"657\",\"658\",\"659\",\"660\",\"661\",\"662\",\"663\",\"664\",\"665\",\"666\",\"667\",\"668\",\"669\",\"670\",\"671\",\"672\",\"673\",\"674\",\"675\",\"676\",\"677\",\"678\",\"679\",\"680\",\"681\",\"682\",\"683\",\"684\",\"685\",\"686\",\"687\",\"688\",\"689\",\"690\",\"691\",\"692\",\"693\",\"694\",\"695\",\"696\",\"697\",\"698\",\"699\",\"700\",\"701\",\"702\",\"703\",\"704\",\"705\",\"706\",\"707\",\"708\",\"709\",\"710\",\"711\",\"712\",\"713\",\"714\",\"715\",\"716\",\"717\",\"718\",\"719\",\"720\",\"721\",\"722\",\"723\",\"724\"],[\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Tuyen Quang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Yen Bai\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Ha Giang\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Quang Ninh\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\",\"Bac Giang\"],[\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\"],[\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Kinh\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\",\"Ethnic minority\"],[\"1\",\"1\",\"3\",\"1\",\"1\",null,\"3\",\"1\",\"3\",\"1\",\"1\",\"1\",\"2\",\"1\",null,\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"3\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",null,\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",null,\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,null,\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"3\",\"2\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"2\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"2\",\"3\",\"3\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"3\",\"1\",\"3\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"3\",\"2\",\"1\",\"2\",\"2\",\"2\",\"1\",\"2\",\"1\",\"3\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"3\",\"2\",\"3\",\"3\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"3\",\"1\",\"3\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",null,\"1\",\"3\",\"3\",null,\"1\",\"1\",\"1\",\"1\",null,\"3\",\"3\",\"3\",\"3\",null,\"1\",null,\"3\",null,\"2\",null,\"3\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"2\",\"3\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"1\",\"1\",\"2\",\"2\",\"1\",\"3\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",null,null,\"3\",\"1\",\"1\",\"3\",\"3\",null,null,\"3\",\"3\",\"2\",\"3\",null,null,\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",null,\"3\",\"3\",\"3\",\"3\",\"3\",null,\"2\",\"2\",\"3\",\"1\",\"2\",\"3\",\"3\",\"2\",\"1\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",null,\"3\",\"1\",\"3\",\"3\",\"2\",null,\"3\",\"1\",\"1\",\"1\",\"1\",null,null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"3\",\"3\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"2\",\"3\",\"2\",\"2\",\"2\",\"2\",\"2\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"3\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\"],[\"3\",\"5\",\"3\",\"3\",\"3\",\"4\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"3\",\"5\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"3\",\"1\",\"2\",\"2\",\"3\",\"4\",\"3\",\"3\",\"3\",\"2\",\"3\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"3\",\"2\",\"3\",\"3\",\"4\",\"3\",\"5\",\"3\",\"2\",\"3\",\"3\",\"2\",\"3\",\"3\",\"3\",\"2\",\"3\",\"2\",\"1\",\"3\",\"3\",\"3\",\"4\",\"5\",\"5\",\"5\",\"4\",\"5\",\"4\",\"5\",\"4\",\"5\",\"4\",\"4\",\"2\",\"4\",\"4\",\"2\",\"5\",\"2\",\"3\",\"4\",\"4\",\"3\",\"4\",\"3\",\"5\",\"4\",\"4\",\"2\",\"5\",\"5\",\"3\",\"1\",\"2\",\"2\",\"3\",\"4\",\"3\",\"4\",\"2\",\"3\",\"3\",\"3\",\"2\",\"5\",\"4\",\"3\",\"4\",\"3\",\"3\",\"5\",\"5\",\"5\",\"5\",\"3\",\"3\",\"3\",\"3\",\"5\",\"5\",\"1\",\"3\",\"2\",\"1\",\"3\",\"5\",\"5\",\"3\",\"5\",\"3\",\"5\",\"5\",\"5\",\"3\",\"5\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"5\",\"3\",\"4\",\"5\",\"5\",\"5\",\"3\",\"3\",\"5\",\"2\",\"1\",\"5\",\"3\",\"3\",\"3\",\"2\",\"3\",\"3\",\"1\",\"4\",\"4\",\"3\",\"2\",\"1\",\"2\",\"1\",\"2\",\"2\",\"3\",\"3\",\"3\",\"2\",\"3\",\"4\",\"5\",\"2\",\"3\",\"3\",\"3\",\"1\",\"2\",\"2\",\"2\",\"5\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"3\",\"2\",\"3\",\"3\",\"3\",\"5\",\"4\",\"5\",\"5\",\"3\",\"2\",\"5\",\"3\",\"3\",\"5\",\"5\",\"5\",\"4\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",\"3\",\"4\",\"3\",\"4\",\"4\",\"3\",\"1\",\"3\",\"3\",\"2\",\"3\",\"3\",\"3\",\"2\",\"5\",\"3\",\"5\",\"3\",\"4\",\"5\",\"4\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"4\",\"5\",\"5\",\"3\",\"3\",\"5\",\"3\",\"4\",\"5\",\"3\",\"3\",null,\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",\"2\",\"2\",\"3\",\"5\",\"3\",\"3\",\"3\",\"5\",\"5\",\"5\",\"5\",\"3\",\"3\",\"3\",\"2\",\"3\",\"3\",\"5\",\"2\",\"3\",\"5\",\"2\",\"2\",\"2\",\"3\",\"3\",\"4\",\"5\",\"4\",\"4\",\"5\",\"4\",\"5\",\"4\",\"4\",\"4\",\"4\",\"4\",\"5\",\"5\",\"5\",\"5\",\"4\",\"4\",\"4\",\"4\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"4\",\"4\",\"4\",\"4\",\"5\",\"4\",\"4\",\"5\",\"4\",\"5\",\"4\",\"5\",\"4\",\"5\",\"5\",\"5\",\"4\",\"4\",\"4\",\"4\",\"3\",\"4\",\"4\",\"4\",\"5\",\"5\",\"4\",\"4\",\"2\",\"3\",\"5\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",null,\"1\",\"3\",\"3\",\"4\",\"3\",\"1\",\"5\",\"5\",\"5\",\"3\",\"3\",\"3\",\"3\",\"4\",\"3\",\"5\",\"2\",\"2\",\"3\",\"3\",\"1\",\"2\",\"2\",\"3\",\"2\",\"1\",\"3\",\"1\",\"3\",\"2\",\"3\",\"2\",\"2\",\"1\",\"1\",\"3\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"5\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"4\",\"5\",\"5\",\"5\",\"5\",\"4\",\"5\",\"5\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"4\",\"4\",\"5\",\"5\",\"5\",\"4\",\"5\",\"3\",\"5\",\"4\",\"3\",\"4\",\"5\",\"5\",\"4\",\"5\",\"5\",\"5\",\"5\",\"5\",\"4\",\"4\",\"5\",\"5\",\"4\",\"4\",\"5\",\"4\",\"4\",\"5\",\"5\",\"5\",\"5\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",null,\"1\",\"3\",\"5\",\"3\",\"3\",\"5\",\"3\",\"3\",\"2\",\"3\",\"5\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"3\",\"2\",\"4\",\"3\",\"3\",\"2\",\"2\",\"3\",\"5\",\"3\",\"5\",\"4\",\"3\",\"5\",\"3\",\"3\",\"3\",\"4\",\"5\",\"3\",\"3\",\"5\",\"5\",\"4\",\"3\",\"3\",\"3\",\"4\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",\"4\",\"3\",\"3\",\"3\",\"3\",\"5\",\"3\",\"3\",\"5\",\"5\",\"4\",\"3\",\"4\",\"5\",\"5\",\"4\",\"4\",\"4\",\"4\",\"2\",\"3\",\"3\",\"2\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"3\",\"5\",\"5\",\"5\",\"5\",\"3\",\"5\",\"2\",\"2\",\"1\",\"1\",\"3\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",\"5\",\"4\",\"3\",\"5\",\"2\",\"2\",\"3\",\"4\",\"4\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"2\",\"4\",\"5\",\"5\",\"5\",\"2\",\"2\",\"3\",\"4\",\"4\",\"4\",\"3\",\"5\",\"4\",\"5\",\"5\",\"5\",\"5\",\"4\",\"4\",\"4\",\"5\",\"5\",\"3\",\"3\",\"5\",\"3\",\"1\",\"1\",\"2\",\"4\",\"3\",\"3\",\"3\",\"4\",\"5\",\"3\",\"1\",\"4\",\"4\",\"4\",\"3\",\"3\",\"4\",\"4\",\"3\",\"3\",\"3\",\"2\",\"2\",null,\"3\",\"3\",\"3\",\"2\",\"1\",\"2\",\"3\",\"2\",\"5\",\"5\",\"3\",\"4\",\"4\",\"5\",\"5\",\"5\",\"5\",\"3\",\"4\",\"4\",\"3\",\"3\",\"5\",\"5\",\"5\",\"5\"],[37,25,33,35,36,21,35,36,38,30,58,24,32,11,22,95,47,38,38,33,44,25,38,29,47,37,38,24,10,33,19,57,90,32,35,34,30,28,20,56,35,48,67,21,36,13,37,26,38,27,28,23,51,47,32,37,73,36,57,120,33,41,27,31,53,21,24,18,28,25,24,22,27,18,23,51,23,21,78,27,78,41,7,23,40,18,54,33,24,22,58,30,36,41,116,58,70,43,29,39,16,75,35,43,35,43,33,44,23,22,32,30,36,33,20,19,35,34,40,32,21,21,138,33,67,124,38,21,20,37,32,44,28,15,14,25,27,20,104,31,35,43,40,33,20,35,27,22,40,35,42,32,50,20,44,22,9,18,22,45,39,26,54,133,16,27,45,50,63,50,25,105,20,24,26,30,103,54,92,43,44,39,22,28,65,45,24,32,45,36,40,40,120,29,37,59,32,42,23,21,39,30,33,35,38,40,24,69,23,40,57,30,29,40,37,40,50,37,26,33,70,28,55,50,28,24,22,35,24,14,39,48,13,44,16,18,20,20,19,30,38,40,42,115,86,40,23,32,26,25,38,180,38,45,36,38,43,39,67,19,31,17,44,19,17,24,39,120,44,37,28,37,14,30,29,44,39,25,43,19,29,48,39,0,40,20,51,41,39,43,61,30,75,76,37,25,35,32,33,28,29,29,17,31,42,32,78,39,37,11,74,33,27,29,46,43,40,30,25,33,21,23,17,23,18,22,21,18,24,31,22,19,19,21,17,18,12,12,21,20,11,18,16,20,27,25,26,22,24,24,24,20,32,20,23,17,25,16,22,19,27,24,24,26,40,27,25,26,23,26,25,26,55,43,33,38,45,39,30,45,28,35,34,10,24,35,50,150,28,38,25,36,150,20,20,20,47,30,38,28,30,32,23,80,77,25,34,99,57,70,51,80,120,24,98,40,90,15,80,70,230,270,60,14,21,24,24,22,15,23,24,18,22,25,25,37,31,33,36,38,48,38,40,37,33,37,37,48,26,29,22,20,20,27,14,13,22,79,52,76,67,57,47,63,68,70,63,74,26,24,19,18,21,24,16,30,19,21,30,24,19,18,24,20,22,19,21,33,30,27,22,21,26,26,21,27,27,17,23,21,20,32,47,36,38,25,37,48,38,39,25,29,36,38,30,40,28,94,38,14,42,45,19,30,29,30,33,19,29,21,37,30,38,46,21,52,25,27,38,54,79,68,34,32,50,19,14,49,21,50,43,69,35,9,35,45,16,12,12,32,46,40,20,35,55,29,17,40,40,67,60,31,32,17,72,38,34,37,33,27,32,34,30,29,41,19,35,30,8,10,28,30,27,17,20,16,18,14,25,45,55,38,52,50,35,60,60,47,30,70,40,3,4,11,16,30,19,100,100,150,150,30,70,30,43,35,38,35,23,28,29,11,79,80,35,23,25,43,31,45,25,46,31,41,560,61,37,27,15,15,11,21,80,68,80,33,19,18,31,21,33,29,20,12,15,8,20,23,33,15,50,27,12,73,80,90,92,25,75,45,50,23,8,36,95,19,10,25,26,15,18,20,33,17,26,35,48,0,25,60,60,90,63,75,60,60,26,13,26,21,15,17,17,18,18,27,23,17,37,39,29,27,13,8],[25,22,25,30,28,17,25,28,26,22,40,24,23,11,20,30,30,28,26,18,28,19,23,23,27,19,23,24,10,33,19,32,35,32,35,25,27,28,20,20,35,32,42,21,15,9,20,26,26,27,25,14,29,26,27,31,33,21,37,53,23,26,26,25,53,21,24,18,28,25,24,18,23,13,23,33,20,21,34,24,37,41,7,18,25,18,20,26,18,17,17,22,28,31,81,43,60,23,29,27,7,53,19,43,20,38,28,32,18,9,26,30,27,28,16,12,30,31,30,32,19,21,45,20,46,57,33,7,11,28,23,24,20,8,11,20,19,20,49,26,27,38,35,13,20,22,22,22,23,35,34,32,40,17,33,19,3,12,12,30,24,26,0,20,10,12,33,36,38,30,23,55,20,24,26,15,53,29,45,28,31,16,20,28,25,45,24,24,27,31,0,5,0,29,37,33,21,35,23,21,39,30,33,30,33,32,0,30,23,35,47,30,20,30,37,35,34,31,26,24,35,28,0,17,0,0,15,35,0,0,17,39,13,19,0,13,18,17,17,25,33,26,36,42,30,30,23,25,23,20,19,0,23,0,0,0,33,33,43,19,22,17,29,19,17,24,34,0,33,22,16,28,14,26,26,39,30,18,30,15,24,38,27,0,40,20,33,31,20,33,37,0,23,24,29,23,27,22,33,20,24,26,17,16,7,32,20,31,29,4,41,33,19,29,31,38,25,19,18,25,16,16,17,15,18,14,16,12,18,21,16,14,14,16,17,16,12,12,21,12,11,18,16,20,21,21,23,22,24,21,24,10,27,17,23,12,15,11,17,15,25,19,14,21,36,22,25,24,20,19,18,22,20,32,33,25,40,31,22,26,24,35,26,10,24,26,20,17,25,30,17,0,85,17,15,16,47,0,35,28,30,0,23,70,30,25,26,29,40,35,36,30,120,17,0,40,0,15,0,0,100,90,60,14,18,24,24,22,15,23,24,17,22,25,17,37,26,25,21,33,33,23,29,28,22,25,28,48,26,29,22,20,18,12,8,8,16,11,21,39,25,22,24,31,21,25,30,38,26,24,17,13,15,20,16,0,19,21,15,24,19,18,24,20,22,19,21,25,24,25,22,21,23,26,17,22,23,17,22,21,0,32,37,28,31,22,0,13,5,18,17,22,21,18,20,10,22,32,23,8,27,30,19,20,16,0,33,19,21,16,29,15,26,27,15,32,25,12,30,30,22,22,19,0,26,19,14,29,20,40,28,54,30,9,35,35,0,4,5,17,28,40,0,0,0,29,11,0,10,32,32,8,0,17,16,13,19,23,7,25,17,22,30,29,31,19,23,15,8,10,28,30,27,13,20,16,18,14,25,45,45,23,22,20,20,0,30,17,30,0,12,3,4,11,16,20,19,60,60,70,50,25,50,25,13,25,23,25,23,28,21,11,24,20,25,23,20,22,26,35,10,26,21,10,340,36,23,14,10,15,11,16,40,33,35,15,13,18,13,21,33,29,20,12,9,8,20,16,16,15,34,6,12,73,0,40,92,17,40,20,20,15,8,12,45,19,10,25,9,15,18,20,13,17,26,35,35,0,25,20,20,35,0,40,20,35,21,13,26,21,15,9,6,7,7,7,20,14,30,35,8,22,5,14],[7,0,0,5,0,0,0,0,12,2,0,0,0,0,0,50,17,10,12,15,0,0,0,6,20,18,7,0,0,0,0,0,20,0,0,0,3,0,0,14,0,4,25,0,0,0,17,0,0,0,3,0,22,12,0,0,25,5,0,25,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,18,0,0,28,3,21,0,0,0,0,0,16,0,0,0,20,9,0,0,36,0,0,0,0,0,1,0,0,0,15,5,5,0,0,3,6,0,0,0,0,0,5,0,0,0,0,0,48,0,21,15,5,14,5,9,0,20,0,0,3,5,8,0,0,0,8,5,0,20,0,0,0,0,6,0,8,0,10,0,11,3,0,0,0,0,0,0,40,88,0,0,0,8,15,20,0,40,0,0,0,15,40,15,35,15,0,15,2,null,15,0,0,0,0,0,0,20,35,0,0,26,3,0,0,0,0,0,0,0,5,0,15,30,0,0,0,0,0,10,0,5,8,6,0,9,10,0,15,13,7,0,0,0,8,10,14,0,0,15,10,5,2,3,2,0,3,5,6,28,30,10,0,7,3,0,0,0,15,0,36,38,5,6,24,0,9,0,0,0,0,0,0,66,11,0,0,9,0,4,0,0,9,6,13,0,0,10,5,null,0,0,18,10,10,10,24,0,25,19,0,2,0,0,0,8,5,0,0,15,10,0,10,8,8,7,20,0,8,0,15,5,0,0,0,0,0,2,0,2,0,5,0,0,0,2,0,0,0,3,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,0,0,7,0,0,5,0,0,5,0,0,0,0,0,4,0,63,3,0,0,36,15,0,0,0,0,0,3,0,0,7,0,0,25,0,0,35,0,0,4,0,0,0,18,0,0,0,0,30,70,0,0,0,3,0,0,0,0,0,0,1,0,0,3,0,5,0,0,5,0,0,11,9,0,0,0,0,0,0,0,0,0,0,0,0,0,20,15,31,7,0,15,24,25,10,11,17,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,0,2,0,0,2,0,0,2,2,0,2,0,20,0,10,8,7,3,19,15,12,0,0,0,0,0,0,30,0,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,18,0,17,0,0,0,0,0,10,0,15,5,0,0,0,10,0,0,0,0,0,0,0,20,0,4,15,0,0,0,3,5,0,40,0,5,0,11,2,15,2,0,0,0,0,0,15,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,30,15,60,30,30,0,70,0,0,0,0,0,5,0,20,20,10,50,5,0,5,30,5,0,10,0,0,8,0,0,0,0,0,5,13,5,0,10,0,0,null,100,0,14,0,0,0,0,0,0,35,45,0,6,null,0,0,0,0,0,0,0,0,0,0,0,0,16,7,0,0,0,50,0,0,35,0,0,0,0,0,50,0,0,0,7,0,0,0,0,0,0,0,0,null,0,30,20,30,23,0,20,0,5,0,0,0,0,8,0,11,11,20,3,3,4,4,0,0,0,0],[5,3,8,0,8,4,10,8,0,6,18,0,9,0,2,15,0,0,0,0,16,6,15,0,0,0,8,0,0,0,0,25,35,0,0,9,0,0,0,22,0,12,0,0,21,4,0,0,12,0,0,9,0,9,5,6,15,10,20,42,10,15,1,6,0,0,0,0,0,0,0,4,0,5,0,0,3,0,16,0,20,0,0,5,15,0,18,7,6,5,21,-1,8,10,-1,15,10,20,0,12,8,22,16,0,0,0,0,12,5,10,0,0,9,5,4,7,0,3,10,0,2,0,45,13,0,52,0,0,4,0,9,0,8,7,0,0,0,0,55,5,0,0,5,0,0,13,5,0,11,0,0,0,0,3,0,0,6,6,10,15,15,0,14,25,6,15,12,6,10,0,2,10,0,0,0,0,10,10,12,0,13,8,0,0,25,0,0,8,18,5,40,15,85,0,0,0,8,7,0,0,0,0,0,5,0,8,9,9,0,5,10,0,9,0,0,0,8,0,0,0,25,0,40,20,21,24,7,0,16,4,8,9,0,10,6,0,0,0,0,5,2,9,0,45,26,0,0,0,0,5,19,180,0,45,0,0,5,0,0,0,0,0,15,0,0,0,5,54,0,15,12,0,0,0,3,5,0,1,0,4,5,0,7,0,0,0,0,0,9,0,0,30,27,33,8,0,8,10,0,0,0,3,0,0,25,0,48,0,0,0,13,0,0,0,0,0,15,11,7,8,5,5,0,6,0,3,5,6,6,8,6,5,5,2,0,0,0,0,0,8,0,0,0,0,6,4,3,0,0,3,0,10,0,3,0,5,10,5,5,4,2,5,10,5,4,5,0,2,3,7,0,4,35,4,0,13,0,8,8,14,4,0,8,0,0,5,30,70,0,8,8,0,50,3,5,4,0,30,0,0,0,25,0,10,22,0,8,35,17,35,11,50,0,7,80,0,90,0,80,40,60,180,0,0,0,0,0,0,0,0,0,0,0,0,5,0,0,8,15,0,15,15,0,0,11,12,9,0,0,0,0,0,2,15,6,5,6,48,16,6,35,35,8,8,22,35,22,19,0,0,2,5,6,4,0,30,0,0,0,0,0,0,0,0,0,0,0,8,6,0,0,0,1,0,4,3,2,0,-1,0,0,0,0,0,0,0,18,20,21,21,8,7,15,20,10,0,6,40,15,6,15,15,0,10,13,30,0,0,8,5,8,15,12,19,6,20,0,15,8,24,35,28,15,15,24,0,0,20,1,0,15,0,0,0,0,10,6,8,7,15,18,0,20,35,35,0,2,25,30,35,28,20,27,0,16,25,10,14,15,0,0,10,0,0,10,0,12,0,0,0,0,0,0,4,0,0,0,0,0,0,10,0,30,0,0,0,0,0,0,0,28,0,0,0,0,5,0,20,20,70,50,0,20,0,0,5,15,0,0,0,0,0,55,60,10,0,0,8,0,10,5,20,10,31,120,25,0,13,5,0,0,5,40,0,0,18,0,0,18,0,0,0,0,0,6,0,0,7,17,0,0,14,0,0,80,0,0,8,0,25,30,8,0,24,0,0,0,0,10,0,0,0,20,0,0,0,13,0,0,10,20,25,40,35,20,25,0,0,0,0,0,0,11,0,0,0,0,0,3,0,21,5,8,-6],[\"1\",\"0\",\"1\",\"1\",\"0\",\"0\",\"3\",\"0\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"0\",\"0\",\"3\",\"2\",\"1\",\"0\",\"0\",\"1\",\"0\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"0\",\"2\",\"0\",\"2\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"3\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"2\",\"0\",\"0\",\"2\",\"2\",\"2\",\"2\",\"0\",\"0\",\"2\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"3\",\"1\",\"2\",\"1\",\"0\",\"1\",\"0\",\"2\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"2\",\"0\",\"0\",\"0\",\"3\",\"0\",\"2\",\"2\",\"0\",\"0\",\"3\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"3\",\"1\",\"1\",\"0\",\"0\",\"1\",\"0\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"2\",\"1\",\"0\",\"0\",\"0\",\"0\",\"2\",\"0\",\"0\",\"3\",\"0\",\"0\",\"0\",\"2\",\"3\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"0\",\"0\",\"2\",\"0\",\"0\",\"1\",\"3\",\"2\",\"1\",\"2\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"2\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"2\",\"0\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"2\",\"2\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"2\",\"0\",\"1\",\"2\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"2\",\"0\",\"3\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",null,\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"2\",\"2\",\"2\",\"2\",\"1\",\"0\",\"1\",\"0\",\"2\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",null,\"2\",\"2\",\"2\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"2\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"1\",\"2\",\"0\",\"0\",\"1\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"2\",\"1\",\"0\",\"3\",\"0\",\"2\",\"0\",\"3\",\"2\",\"0\",\"2\",\"1\",\"2\",\"0\",\"0\",\"1\",\"3\",\"3\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"2\",\"0\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"2\",\"3\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"3\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"2\",\"1\",\"1\",\"1\",\"1\",null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,\"1\",\"3\",null,null,\"2\",null,null,null,null,null,\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",\"1\",\"1\",\"0\",\"0\",\"1\",\"3\",\"0\",\"1\",\"2\",\"0\",\"0\",\"0\",\"0\",\"1\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"2\",\"2\",\"2\",\"1\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"1\",\"1\",null,\"0\",\"0\",\"0\",\"1\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\",\"2\",\"0\",\"0\",\"0\",\"0\",\"0\",\"0\"],[\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"2\",\"2\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",null,null,null,null,null,\"2\",null,null,null,null,null,null,null,null,\"1\",\"2\",null,null,\"2\",null,null,null,null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\"],[\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",null,\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",null,\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Medium\",\"Medium\",\"Medium\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Low\",\"Medium\",\"Low\",\"Low\",\"Medium\",\"Medium\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Low\",\"Medium\"],[\"1\",\"1\",\"2\",null,\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",null,null,\"2\",null,\"2\",null,\"2\",null,null,\"2\",\"2\",\"2\",null,\"2\",\"2\",\"2\",null,\"2\",null,\"2\",\"2\",\"1\",\"2\",null,\"1\",null,\"2\",null,\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",null,\"2\",null,\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",null,\"2\",\"2\",\"1\",\"2\",null,\"1\",\"2\",\"1\",null,\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"2\",\"2\",\"1\",\"2\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"2\",\"2\",\"2\",\"1\",null,\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",null,null,\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",null,\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",null,\"2\",\"1\",null,\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"1\",null,\"1\",\"1\",\"2\",\"1\",\"1\",null,\"1\",\"2\",\"2\",\"2\",null,null,null,\"2\",null,\"2\",null,null,\"2\",\"1\",\"2\",\"2\",\"1\",\"2\",\"2\",null,null,null,\"2\",null,\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",null,null,\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",null,\"2\",\"1\",\"1\",\"2\",\"2\",\"2\",null,\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"1\",null,\"1\",\"1\",\"1\",null,\"1\",null,null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"2\",\"2\",null,\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"2\",null,\"1\",null,\"2\",null,\"1\",null,\"1\",null,\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",null,null,\"2\",\"2\",\"1\",null,\"1\",\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"1\",null,\"2\",\"1\",\"1\",\"2\",null,\"2\",\"2\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",null,\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",null,\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"2\",\"1\",null,\"2\",\"2\",\"2\",\"2\",\"2\",null,\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",null,\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",null,\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",null,\"2\",\"1\",\"2\",null,null,\"1\",\"2\",null,null,\"2\",null,null,\"2\",null,\"2\",\"2\",\"2\",null,null,\"1\",\"2\",null,\"2\",null,\"1\",\"2\",null,null,\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"2\",null,null,\"1\",\"2\",\"1\",\"1\",\"1\",null,null,null,null,\"2\",null,\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",null,\"1\",null,\"2\",\"2\",\"1\",\"2\",null,\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",null,null,\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",null,\"2\",\"1\",\"2\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",null,\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"2\",\"1\",\"2\",\"2\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"1\",\"1\"],[null,1,null,1,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,1,null,null,null,1,1,null,1,null,1,1,null,1,1,1,1,1,1,null,1,1,null,null,null,null,null,1,1,1,null,null,null,null,null,1,1,null,1,1,null,null,null,1,1,null,1,null,1,1,1,null,null,null,null,null,1,1,null,1,null,1,1,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,1,1,1,1,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,1,1,1,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,1,null,1,1,null,null,1,null,null,1,1,1,1,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,1,null,1,null,null,1,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,null,null,null,null,null,null,1,null,null,1,null,null,null,null,null,null,1,null,1,1,null,1,null,null,null,null,1,1,1,1,1,null,1,null,null,1,1,1,1,1,1,null,null,null,null,1,null,null,1,1,1,1,1,1,1,1,1,null,null,null,null,null,null,null,null,1,1,null,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,1,1,1,null,null,null,null,null,1,1,null,null,null,null,null,null,null,1,null,null,1,null,null,null,null,null,null,null,null,null,1,1,1,1,1,1,1,1,1,1,null,1,null,1,null,1,null,null,null,1,null,1,1,1,null,null,null,1,1,1,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,1,1,1,1,null,1,1,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,1,null,1,1,1,1,null,null,null,null,1,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,1,1,1,null,null,null,1,1,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,1,1,null,null,null,null,null,null,null,null,null,null,null,1,null,1,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,1,1,null,null,null,null,1,null,null,1,null,null,1,1,1,1,1,null,null,1,null,null,1,null,null,null,null,1,null,null,null,1,1,null,null,null,1,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,1,1,1,1,null,null,null,null,null,1,1,1,1],[1,null,null,null,1,1,null,1,1,1,1,1,null,1,null,null,null,null,null,null,null,null,null,1,null,null,null,1,1,1,null,1,null,null,null,null,1,null,1,1,null,1,null,1,1,null,1,1,1,null,1,1,null,1,1,1,null,1,null,null,1,1,1,1,1,1,1,1,1,1,null,1,null,1,1,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,1,null,null,null,1,null,null,null,null,1,null,1,null,null,null,1,null,null,1,1,1,null,null,1,null,null,null,null,null,null,1,null,null,1,null,null,1,null,1,null,null,null,1,null,1,null,1,null,1,1,1,1,null,1,1,1,1,null,1,1,null,1,null,null,null,null,1,1,1,null,null,null,1,1,1,null,null,1,null,1,1,1,null,null,null,null,null,null,1,1,1,null,1,null,null,null,1,1,null,null,null,null,null,null,null,null,null,1,null,1,null,1,1,null,null,1,null,1,1,1,1,1,1,1,null,null,1,null,1,null,1,1,1,null,1,null,null,1,null,null,1,null,null,null,null,null,1,1,1,1,null,null,1,1,1,1,null,1,null,1,1,null,null,1,1,null,null,1,null,1,1,null,1,1,null,1,1,1,1,1,null,1,1,1,1,1,1,null,1,1,null,1,1,1,1,1,1,null,null,null,null,1,1,1,1,1,1,1,null,null,1,null,1,null,1,null,null,null,1,null,null,null,null,1,null,1,null,1,null,null,1,null,1,1,1,1,null,null,null,null,null,1,null,1,1,null,null,null,null,null,null,1,1,1,1,null,1,1,null,null,null,null,null,null,null,null,null,1,1,1,1,null,1,1,1,null,null,1,null,null,null,1,1,1,1,1,1,1,1,1,1,1,1,null,null,1,1,null,null,null,null,null,null,1,null,1,1,1,null,null,null,null,null,1,null,null,null,null,null,null,null,null,1,null,1,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,1,null,1,null,1,null,1,1,1,null,1,null,null,null,1,1,1,null,null,null,null,1,null,1,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,1,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,1,1,1,1,1,null,1,1,1,1,1,null,null,null,null,null,1,1,1,1,1,null,1,null,1,null,1,1,null,null,null,null,1,null,null,1,1,null,null,null,null,1,null,null,1,1,1,1,1,null,1,null,null,null,null,null,null,1,1,1,1,null,null,null,null,1,null,1,null,1,null,1,null,1,1,1,1,1,1,1,null,null,null,null,null,1,null,null,null,1,null,1,1,1,1,1,1,null,1,1,null,null,1,1,1,1,1,null,1,null,null,null,null,1,1,null,null,null,null,null,null,null,null,1,null,null,null,1,1,null,null,null,null,1,1,null,1,1,1,1,1,1,null,null,null,null,null,null,null,null,null,null,1,1,null,1,1,null,1,1,null,null,null,null,null,1,1,null,1,null,null,1,null,null,null,null,null,1,1,null,null,1,null,1,null,1,null,1,1,1,1,null,1,null,null,null,1,null,1,null,null,null,1,null,null,1,1,1,1,null,null,null,null,1,1,1,1,1,null,null,null,null],[null,null,null,null,null,null,1,null,null,null,null,null,1,null,null,1,1,1,1,1,1,1,1,null,null,1,null,null,null,null,1,null,1,1,null,1,null,null,null,null,null,null,1,null,null,null,null,null,null,1,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,1,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,1,null,null,null,1,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,1,null,null,1,null,null,1,null,null,null,null,null,null,null,1,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,1,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,1,null,1,null,null,1,1,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,1,null,null,null,null,null,1,null,null,null,null,1,null,null,1,1,null,null,null,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,1,1,1,1,1,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,1,null,1,null,null,null,null,null,null,null,1,null,1,1,null,null,1,1,null,1,null,1,null,null,null,null,null,null,1,null,null,1,null,null,null,null,null,null,null,null,null,1,1,1,null,1,null,1,null,null,null,1,null,null,null,null,null,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,null,1,1,null,null,1,null,null,null,null,null,1,1,null,null,1,null,null,null,null,null,null,null,1,1,1,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,1,null,1,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,1,null,null,1,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,1,null,null,null,null,null,null,null,1,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,1,null,null,null,null,null,null,null,null,null,1,null,null,null,1,null,1,null,null,null,null,1,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,null,null,null,null,1,1,null,1,null,null,null,1,null,null,1,1,null,null,null,null,null,null,null,null,1,null,null,1,1,1,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,1,1,null,null,1,null,null,null,null,null,null,null,null,1,1,null,null,null,null,null,null,1,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,1,1,null,1,null,1,null,null,null,null,1,null,null,null,null,1,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,null,null,null,null,null,1,null,null,null,null,null,null,null,1,1,1,null,null,1,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,1,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[null,15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,22,null,null,null,null,null,null,null,5,30,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,6,null,null,null,null,null,null,null,null,null,null,null,10,null,7,6,50,null,null,10,null,null,null,null,5,null,5,10,null,null,null,null,null,null,null,null,null,null,6,null,null,null,null,null,null,10,null,3,null,null,null,null,null,5,null,25,null,null,null,null,null,null,null,null,10,null,null,null,11,10,24,null,null,null,5,null,null,null,null,null,null,10,null,null,null,null,null,null,20,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,9,null,null,null,null,10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,null,null,null,null,null,null,null,null,null,null,null,null,null,10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,20,null,null,null,10,null,null,null,null,null,null,null,null,null,10,null,null,null,null,null,null,null,null,null,7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,30,null,null,null,null,null,null,null,null,null,7,null,null,null,null,null,null,7,86,50,null,null,null,null,null,null,null,null,10,null,null,null,null,null,null,null,null,null,null,null,8,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,7,15,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,15,null,null,null,null,null,null,null,null,null,null,null,20,null,null,null,null,null,8,null,null,null,null,null,null,null,null,null,null,10,20,10,null,null,null,null,null,8,null,null,null,null,null,100,null,600,0,500,null,null,null,30,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,7,null,null,7,null,5,10,7,7,7,7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,23,null,null,null,null,null,null,null,null,null,null,null,null,20,null,null,null,4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,8,null,8,null,null,8,null,null,null,8,null,null,100,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,10,null,null,10,null,null,15,null,null,null,null,10,null,null,null,null,20,null,10,null,null,null,null,null,null,20,20,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,30,null,null,null,25,36,null,null,null,20,null,null,10,null,10,null,26,null,null,5,10,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,20],[5,null,30,null,null,2,70,null,25,10,15,null,null,16,null,20,null,null,null,15,10,15,null,null,null,null,1,null,null,null,null,10,14,1,null,null,null,null,null,null,null,null,18,null,15,2,null,null,null,null,null,null,21,null,2,null,null,null,null,null,null,null,18,null,null,null,null,5,null,null,6,null,null,null,null,null,null,null,50,4,null,null,null,null,null,null,null,null,null,null,80,null,null,null,null,null,null,null,null,20,null,16,6,15,80,null,null,null,null,null,null,4,4,null,null,null,null,null,null,null,null,null,13,null,17,28,4,null,null,null,null,5000,null,null,null,null,null,null,null,null,null,null,null,null,null,null,5,null,null,null,26,null,null,null,null,null,null,null,null,15,10,null,20,30,null,null,null,null,null,10,10,10,null,null,null,null,null,null,null,2,null,10,null,null,null,null,null,null,null,null,null,null,20,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,10,20,null,null,10,5,5,null,null,null,null,null,null,null,null,null,null,3,null,5,null,null,null,null,null,null,null,null,null,null,6,null,1,2,4,null,1,null,null,2,null,null,2,25,0,6,30,null,null,null,null,null,null,null,null,null,null,1,4,null,4,null,null,null,20,30,null,null,null,null,null,1,5,null,null,null,null,null,null,null,null,null,null,null,null,null,9,null,null,null,null,null,null,10,null,null,2,null,null,null,null,2,null,null,null,null,null,null,null,null,null,null,2,2,3,null,3,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,20,50,null,null,null,null,100,null,null,null,21,10,20,20,15,12,40,null,15,3,2,40,7,15,20,500,200,0,70,null,100,25,0,0,null,null,0,null,null,null,null,null,null,12,9,6,8,9,8,9,6,7,7,4,12,6,7,null,null,null,null,null,null,null,null,null,11,9,19,7,10,16,11,8,11,9,7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,10,null,null,5,null,5,null,20,1,null,null,null,8,null,null,null,10,null,null,null,4,null,null,null,null,10,30,2,30,null,null,null,null,null,null,4,15,null,null,8,6,8,6,null,null,null,null,null,null,10,null,30,2,8,null,null,null,null,null,null,null,null,null,null,null,5,null,7,null,null,null,1,null,2,5,null,4,30,10,null,null,null,null,null,null,null,null,2,null,null,null,null,null,null,null,10,null,20,20,null,null,null,null,null,null,null,null,30,null,null,40,50,30,20,80,20,110,15,null,null,3,null,null,null,4,15,null,null,4,20,10,null,15,10,null,null,50,32,8,11,4,null,1,3,null,36,10,11,null,null,null,null,null,null,null,null,null,null,null,null,null,null,86,12,null,50,130,60,70,10,7,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,17,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],[240,350,260,300,360,360,260,260,300,300,270,null,null,200,null,200,null,null,null,200,200,270,null,null,180,null,300,300,300,300,300,300,300,300,300,360,null,320,300,320,300,240,300,300,350,350,350,300,320,305,150,165,200,150,120,120,230,300,365,60,60,60,60,260,270,260,270,270,270,270,260,null,180,180,100,500,180,180,147,218,null,240,180,180,210,210,null,null,null,null,155,150,150,160,90,130,200,200,180,200,180,300,300,300,180,180,200,210,365,180,210,300,300,270,270,270,365,300,30,60,180,180,300,310,300,190,180,null,95,63,240,240,240,360,null,null,280,280,360,180,180,180,180,null,null,null,null,330,null,300,null,180,null,200,180,20,null,null,180,365,null,null,null,null,null,null,180,null,180,null,null,null,null,300,null,null,300,300,null,null,null,null,null,300,null,null,300,300,300,300,null,null,null,null,null,null,300,null,80,80,80,40,180,180,180,180,null,null,null,180,180,180,180,180,180,180,180,180,null,180,null,null,null,null,365,null,null,null,null,null,null,null,null,180,null,320,320,320,null,345,350,210,300,320,300,370,200,null,200,200,280,null,300,null,null,null,180,180,240,210,150,null,210,180,210,250,200,null,250,150,180,365,120,265,245,360,200,null,360,null,null,null,90,null,270,302,null,300,320,120,90,80,80,null,115,0,120,null,null,60,90,300,null,90,90,90,90,85,90,20,22,180,null,85,80,90,120,200,30,110,360,360,360,360,260,270,270,200,210,360,null,null,250,300,200,270,200,300,90,200,30,60,140,140,140,140,140,140,140,140,140,35,100,100,70,20,100,30,100,130,90,140,140,30,100,null,60,140,60,80,40,200,150,100,100,10,100,100,100,100,100,100,100,170,200,null,200,250,300,300,150,null,300,340,340,320,300,345,240,100,340,200,300,335,360,340,360,350,340,360,150,90,200,300,248,242,null,240,null,null,335,300,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,null,180,180,180,180,180,180,180,180,180,180,200,200,200,250,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,180,310,300,300,310,300,300,270,300,270,300,300,300,120,220,180,280,150,200,180,280,190,180,300,300,180,180,320,310,310,320,60,320,180,null,null,360,300,null,180,null,null,60,null,null,360,160,null,null,null,180,120,null,null,210,null,null,300,null,360,360,360,null,null,360,360,null,null,null,100,120,null,null,180,180,180,180,300,null,180,180,180,null,200,250,200,180,180,null,null,null,null,30,null,null,null,300,null,150,300,90,300,200,320,300,200,300,200,30,320,310,200,360,100,null,null,null,null,270,270,270,null,270,270,270,300,null,null,null,null,null,null,null,340,null,null,210,180,180,180,180,null,200,100,100,100,150,null,120,null,200,null,null,null,200,null,300,365,180,200,300,250,280,270,260,280,280,300,365,350,300,250,320,200,300,180,291,300,null,300,null,280,90,195,180,200,190,240,240,240,230,200,190,200,150,300,180,300,300,200,205,270,365,60,340,280,300,270,200,100,300,null,340,300,310,300,315,280,230,300,320,300,280,null,60,250,250,100,230,250,280,300,300,300,360,300,300,310,null,300,300,300,300,null,300,300,200,200,200,250],[5,2,5,null,5,2,5,5,4,5,4,null,null,null,null,null,null,null,null,null,null,null,3,null,3,3,2,null,null,null,3,2,3,3,null,null,null,null,null,null,null,1,3,null,2,1,2,1,2,null,2,2,5,null,null,null,3,2,4,null,null,5,null,1,1,1,null,1,1,1,1,null,null,4,5,1,5,5,1,1,null,null,1,1,3,3,2,null,2,2,2,2,2,2,1,2,2,2,1,2,5,null,null,null,null,3,1,2,null,3,3,null,null,null,null,null,null,3,null,2,2,3,null,3,4,5,5,null,null,null,3,3,3,2,4,null,4,4,2,2,2,2,2,5,5,1,5,null,null,4,null,2,2,null,4,null,null,null,null,4,2,4,5,3,2,5,2,null,2,2,4,3,5,null,5,5,5,4,null,null,null,3,null,5,null,null,5,null,5,5,4,4,3,null,null,null,5,null,2,2,1,null,2,2,2,2,null,null,null,2,2,2,2,2,2,2,2,2,null,2,null,3,4,3,4,5,2,3,5,2,5,null,null,1,4,null,3,null,null,2,2,3,0,null,null,2,5,null,3,5,3,null,3,null,null,null,null,null,null,null,null,null,null,null,null,2,3,null,1,null,5,2,5,null,null,null,3,null,3,null,null,null,null,null,3,null,null,null,2,1,5,5,5,null,null,2,2,null,null,null,null,null,null,3,4,4,4,1,1,1,1,null,null,5,5,5,1,2,5,null,4,null,null,null,null,4,4,5,null,null,null,5,5,5,1,1,5,null,null,null,5,null,null,null,null,null,null,2,null,null,null,2,2,2,2,1,2,1,1,1,1,1,1,2,null,2,2,1,2,2,2,5,2,2,2,2,2,2,2,2,2,2,2,3,2,3,4,1,3,2,2,null,5,4,4,4,2,4,3,3,3,1,1,5,3,null,3,1,4,3,2,3,2,1,null,null,4,1,2,4,5,5,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,2,1,1,1,2,1,2,1,1,2,1,1,1,1,1,3,3,2,2,1,1,1,1,1,2,1,2,2,1,2,1,1,1,2,1,1,1,4,4,4,4,4,3,4,4,4,3,5,4,5,5,5,5,5,5,4,3,5,5,1,1,1,2,3,4,4,3,3,3,1,2,null,1,1,1,1,3,3,3,1,null,null,3,1,null,null,2,null,null,null,1,null,null,null,null,1,null,1,null,null,1,1,null,null,null,2,2,null,null,1,1,1,1,2,null,null,1,1,null,null,3,1,1,1,null,null,null,null,null,null,null,null,null,null,4,1,1,2,2,1,2,2,1,1,null,1,2,2,2,1,5,5,4,5,3,3,4,5,5,4,4,null,null,null,null,5,4,5,2,null,5,null,null,null,null,null,null,2,null,4,4,4,3,2,2,2,4,2,null,4,null,null,null,3,3,4,4,4,3,3,3,2,3,3,5,2,4,3,2,2,null,4,2,2,2,4,null,5,2,5,4,4,4,1,1,1,4,4,3,4,3,1,4,1,null,3,3,1,null,null,1,2,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,2,1,1,2,1,1,2,2,1,2,1,1,1,1,2,2,2,1,2,1,1,1,3,2,3,2],[2,5,5,null,5,4,2,2,3,1,1,null,null,null,null,null,null,null,null,null,null,null,null,null,5,1,null,null,null,null,null,1,3,null,null,null,null,null,null,null,null,2,null,null,1,1,1,1,2,null,1,1,5,null,null,null,1,4,1,5,null,3,null,1,2,1,null,1,1,1,1,null,null,5,4,1,5,5,2,3,null,2,1,1,1,1,null,null,null,null,1,1,1,1,1,1,1,1,1,1,5,null,null,null,null,3,2,null,5,2,null,null,null,1,null,null,null,1,4,2,1,1,null,5,2,5,5,null,null,null,2,2,5,2,3,null,3,3,2,3,2,2,2,3,2,1,2,null,null,4,null,2,2,null,2,null,null,null,null,3,2,2,2,3,1,4,2,null,3,1,2,4,2,null,5,5,5,5,null,null,null,2,null,5,null,null,4,null,2,5,2,1,2,null,null,null,4,null,1,1,2,null,2,2,2,2,null,null,null,2,2,2,3,2,2,2,3,2,null,3,null,null,2,4,3,2,1,1,3,3,2,null,null,1,4,null,null,null,null,4,4,null,0,null,null,1,4,null,4,4,3,null,4,null,null,null,null,null,null,null,null,null,null,null,null,2,5,null,null,null,3,3,3,2,null,null,4,null,3,null,5,5,null,null,1,null,null,null,1,1,3,4,3,null,null,2,2,null,null,null,null,null,null,2,3,3,5,2,1,1,1,null,null,4,4,3,1,null,null,null,null,null,null,null,null,3,4,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,1,2,2,2,2,2,1,1,2,1,2,1,1,2,2,2,1,2,2,2,null,2,3,3,3,3,3,3,3,3,3,3,1,2,2,2,5,2,1,2,null,5,null,null,null,2,null,3,5,2,3,1,3,2,1,1,5,2,2,3,3,0,1,null,null,5,3,4,3,4,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,5,4,5,5,5,5,4,5,5,5,5,5,5,5,5,3,5,4,1,5,5,2,1,1,2,5,5,5,5,1,5,1,null,null,null,1,1,1,3,3,3,1,null,null,2,1,null,null,1,null,null,null,1,null,null,null,null,1,2,1,null,null,5,1,null,null,null,1,1,null,null,1,1,1,1,null,1,1,1,1,null,null,null,1,1,1,null,null,null,null,null,null,null,null,null,null,1,1,1,1,1,1,3,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,5,null,null,null,2,4,2,2,null,5,null,null,null,null,null,null,4,null,3,3,3,3,4,3,4,5,4,null,4,null,null,null,2,null,4,3,5,3,3,1,2,1,3,2,1,2,5,5,1,null,4,3,5,3,2,null,5,1,4,4,3,3,1,1,1,3,3,3,3,3,2,2,1,null,2,5,2,null,null,1,1,1,2,2,1,1,1,1,1,1,1,4,1,1,1,1,1,2,null,1,1,1,1,1,1,1,1,1,2,2,1,1,2,1,1,1,2,1,1,1,1,2,1,1,1],[3,3,1,null,1,3,3,3,3,3,3,null,null,1,null,1,null,1,null,1,null,1,1,null,4,4,2,2,3,3,2,3,5,2,5,4,null,2,null,3,3,3,2,3,4,3,null,null,3,5,1,1,3,2,1,1,1,3,2,1,null,1,null,1,1,5,null,1,2,1,1,null,3,4,1,1,1,1,1,4,1,3,2,2,3,2,3,2,3,3,2,3,4,3,3,3,2,3,2,3,1,1,1,2,1,1,2,1,3,2,3,1,null,3,5,2,2,4,3,2,3,2,2,1,4,1,1,2,2,2,1,1,1,2,null,null,1,2,2,1,1,1,1,2,3,4,2,null,1,2,5,1,1,3,1,3,3,3,3,2,2,2,2,2,2,2,1,1,1,2,2,2,2,1,null,1,1,1,null,1,null,2,null,1,null,null,1,4,1,1,2,2,2,null,null,null,1,null,2,2,2,2,1,1,1,1,null,null,null,1,1,1,1,1,1,1,1,1,null,1,null,null,3,2,2,3,2,2,2,2,2,null,4,1,2,2,2,2,5,4,4,2,2,3,2,2,2,null,null,5,5,null,3,null,null,null,2,3,2,1,2,2,null,4,4,3,4,null,4,3,2,3,2,2,1,null,3,null,5,1,1,1,1,null,3,1,5,5,5,3,null,null,null,null,null,3,1,2,null,3,1,null,null,null,1,1,1,2,2,2,2,3,null,3,2,null,2,null,1,3,2,2,2,2,2,1,1,3,null,5,3,1,3,3,4,2,2,2,3,2,1,3,4,4,4,2,2,2,1,2,2,1,1,5,5,4,5,5,2,5,2,3,2,5,null,5,5,2,5,5,5,1,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,3,2,2,4,null,4,4,null,5,3,null,5,1,4,2,2,2,2,1,2,1,2,1,3,3,1,2,4,4,4,2,null,5,1,1,1,2,2,2,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,null,3,3,4,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2,2,3,2,4,2,2,1,2,4,2,2,2,4,3,3,3,3,4,3,3,2,3,3,4,2,1,1,1,2,2,1,1,1,2,2,null,3,3,null,1,2,3,3,3,5,5,1,5,null,5,5,3,5,3,1,5,5,4,5,3,3,3,null,2,3,3,5,5,5,2,2,null,null,1,1,1,1,2,4,4,2,3,null,3,3,1,3,2,2,null,null,null,3,4,2,3,3,4,1,1,1,1,1,1,3,5,3,5,3,3,3,1,2,5,3,3,3,2,3,3,2,3,3,3,3,null,1,4,2,null,2,2,2,2,null,2,null,1,3,4,3,3,2,3,1,1,1,1,2,1,2,2,2,2,4,null,null,4,4,4,2,3,3,2,2,2,4,2,3,2,1,2,3,4,2,4,3,2,5,4,null,2,3,2,4,2,2,3,3,3,2,3,3,2,2,2,2,4,2,1,5,5,null,3,3,3,2,2,3,3,1,4,null,3,3,2,2,1,3,3,2,2,2,null,3,2,3,2,3,3,3,4,2,2,3,4,3,3,3,3,3,3,4,4,4,4,3,3,3,3],[1,1,1,null,1,1,2,2,2,2,2,null,null,3,null,null,null,null,null,1,1,1,null,null,1,1,1,1,1,null,1,2,1,2,2,1,1,null,null,null,1,1,1,2,2,2,1,3,3,3,1,1,1,2,1,2,1,1,1,null,null,1,null,1,1,3,null,1,1,1,1,null,null,1,1,3,1,1,1,1,1,3,1,1,1,1,2,2,2,2,1,1,3,3,1,3,1,1,1,1,1,1,1,1,1,1,2,1,3,1,1,1,1,3,3,3,3,2,3,1,1,1,1,3,1,1,1,null,null,null,1,1,1,null,null,null,1,null,null,1,1,1,1,2,2,null,2,1,1,2,1,1,1,null,1,null,null,null,null,3,3,1,2,2,1,2,1,1,1,3,2,1,2,null,1,2,null,1,3,2,1,1,1,null,null,null,null,1,1,null,null,null,null,null,null,null,null,null,1,1,null,1,1,1,1,1,null,null,null,1,1,1,1,1,1,1,1,1,null,1,null,null,null,null,2,null,null,null,2,2,2,null,null,1,null,1,1,1,1,1,2,1,3,1,1,1,3,3,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,2,1,1,1,1,null,1,1,1,1,1,1,1,1,1,null,null,1,1,1,2,null,1,null,null,1,1,1,1,1,3,3,3,null,null,1,1,1,null,1,1,null,1,2,1,1,1,3,3,1,null,1,1,2,2,2,1,1,null,null,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,2,1,1,3,1,2,1,1,1,1,1,3,1,1,1,1,1,1,3,3,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,3,1,1,1,1,1,1,1,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,2,null,null,null,null,1,1,1,1,1,1,1,1,3,1,2,2,2,2,2,1,2,2,null,null,null,null,null,1,null,1,1,1,1,1,1,1,1,2,1,1,1,null,null,1,1,2,1,2,2,1,1,2,1,1,1,1,2,3,2,1,3,2,3,1,1,1,1,3,null,3,3,null,3,1,3,1,2,3,null,2,1,null,1,2,1,1,1,2,2,1,1,1,2,2,1,2,3,3,3,3,2,2,1,1,2,3,2,2,2,null,1,1,1,1,1,1,1,3,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,2,2,1],[3,1,1,null,1,1,3,3,3,3,3,null,null,1,null,null,null,null,null,2,1,1,null,null,1,3,2,1,1,null,1,1,2,1,2,null,null,null,null,null,2,3,null,2,3,1,3,3,3,null,3,3,2,3,2,1,3,1,2,null,null,3,null,1,1,2,null,1,1,1,1,null,null,1,1,1,1,1,3,2,2,3,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,1,3,1,2,2,null,1,1,3,1,3,2,1,2,2,3,3,3,3,2,3,1,1,1,3,3,2,1,1,null,null,null,2,2,2,null,null,null,2,null,null,1,1,1,1,1,3,null,3,1,2,1,1,1,1,null,1,null,null,null,null,2,3,1,2,3,3,3,2,1,1,2,1,3,1,null,2,2,null,2,3,3,null,3,1,null,null,1,null,1,2,null,2,2,null,null,null,null,null,null,2,2,1,1,1,1,1,1,null,null,null,1,1,1,2,1,1,1,1,1,null,2,null,null,null,null,2,2,2,null,2,null,null,null,null,1,null,1,1,2,1,1,2,3,1,2,null,3,2,3,null,3,3,2,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,2,3,2,1,2,2,1,1,1,1,1,1,2,null,null,1,null,1,1,2,2,1,3,3,3,3,null,null,1,1,1,3,null,1,null,null,3,3,3,3,2,2,2,2,null,null,3,3,3,null,3,3,1,3,2,2,2,2,3,2,3,null,1,1,3,3,2,1,2,null,null,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,1,1,3,2,null,1,1,null,3,3,3,3,3,3,2,2,3,2,2,3,1,2,3,1,3,null,1,1,1,1,1,1,1,1,1,1,1,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,3,1,1,3,1,2,3,1,2,2,2,2,2,2,1,3,1,2,2,3,3,3,2,3,3,3,2,1,2,3,3,1,1,2,1,1,1,1,1,null,null,1,1,2,1,3,3,1,3,2,3,1,3,1,3,3,1,3,1,3,2,3,2,3,3,3,1,1,1,3,3,3,3,3,3,3,3,3,1,1,1,3,3,3,1,2,1,1,1,1,1,1,1,1,1,3,3,3,3,3,1,3,1,2,1,1,1,1,3,3,null,null,null,null,1,1,1,1,1,1,1,2,1,1,3,2,2,3,3,2,2,1,1,null,null,null,null,2,null,3,3,1,2,3,1,3,1,1,2,2,2,null,null,1,1,2,2,2,1,1,1,2,1,1,1,1,2,3,1,3,1,1,1,3,2,2,1,3,null,3,3,3,2,3,3,1,3,3,null,3,3,null,2,2,1,3,3,2,2,1,1,1,3,3,1,3,2,3,2,3,3,3,3,3,3,3,3,3,3,null,2,3,1,1,1,3,3,3,2,3,3,3,1,3,2,3,3,3,3,3,3,3,1,1,1,1],[3,1,1,null,1,1,2,2,2,2,2,null,null,null,null,null,null,null,null,2,null,2,null,null,1,2,1,2,2,null,2,1,1,2,2,null,2,null,2,null,1,1,1,1,1,1,1,3,3,3,1,1,1,2,2,2,1,2,3,null,null,1,null,2,1,3,null,3,1,1,3,null,null,1,1,1,1,1,1,1,2,1,1,1,1,1,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,3,1,1,1,1,3,3,3,3,2,3,2,1,1,1,3,2,1,1,null,null,null,1,1,1,null,null,null,1,null,null,1,1,1,1,3,null,1,2,1,1,1,1,1,1,null,1,null,null,null,null,3,3,2,2,2,2,3,1,null,1,3,3,2,3,null,1,1,null,1,1,1,1,3,null,null,null,null,null,null,1,null,2,2,2,null,null,null,null,1,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,null,2,2,null,2,2,2,2,null,null,null,null,1,2,2,1,2,1,1,1,3,1,3,3,1,1,1,null,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,1,2,2,1,1,1,1,1,2,1,1,1,1,1,2,null,null,1,null,1,1,2,2,null,null,3,2,2,null,null,2,2,1,2,null,1,null,null,1,3,1,3,1,3,3,3,null,null,3,3,3,1,1,1,null,1,null,null,null,null,3,3,1,null,null,1,1,2,2,1,3,null,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,3,3,3,1,1,1,1,1,1,2,1,3,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,3,2,2,3,3,1,1,1,3,1,1,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,3,1,3,1,2,1,1,3,1,1,1,3,1,3,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,null,1,1,1,2,2,2,2,3,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,1,1,null,null,null,null,2,2,2,2,2,2,2,1,null,2,1,2,2,2,2,1,2,1,null,null,null,null,null,1,null,1,1,2,1,1,1,2,1,1,2,2,2,null,null,1,1,1,1,1,2,1,1,1,2,2,1,1,2,1,1,1,1,2,1,1,1,1,1,1,null,1,1,1,1,2,3,1,1,1,1,1,1,null,1,2,2,3,3,1,1,3,1,1,3,1,1,3,2,3,3,1,3,3,3,3,1,2,1,3,2,null,2,3,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,null,1,1,1,1,1,2,1,null,null,2,null,null,null,null,null,1,null,2,null,null,1,1,2,1,1,null,1,1,1,1,null,null,1,null,null,null,1,3,3,1,1,2,1,1,1,1,1,1,1,2,1,1,2,3,3,null,null,1,null,1,3,1,null,1,1,1,1,null,null,2,1,null,1,1,1,1,2,3,1,1,1,1,3,3,3,3,2,2,2,3,2,2,1,1,1,3,1,1,1,1,2,1,1,1,3,1,1,1,1,3,3,3,3,1,3,1,1,1,3,2,2,1,1,null,null,null,1,1,1,null,null,null,1,null,null,1,1,1,1,1,1,null,1,null,2,1,null,1,1,null,1,null,null,null,null,1,3,2,1,1,3,1,1,null,1,3,1,2,1,null,1,1,null,1,1,1,1,2,1,null,null,null,null,null,1,null,1,1,2,null,null,null,null,1,1,2,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,null,null,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,2,2,3,3,1,1,1,1,1,null,1,1,1,1,1,1,1,1,3,1,3,null,3,1,3,2,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,null,1,null,1,1,null,null,null,3,1,1,1,null,null,1,1,1,2,null,1,null,null,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,null,null,null,null,3,3,1,null,null,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,1,1,1,1,3,3,1,1,1,1,1,1,1,3,3,3,3,3,3,3,1,3,3,null,null,3,3,3,3,1,1,3,3,1,3,1,3,3,1,1,1,1,3,1,1,1,1,3,3,3,3,1,3,1,3,3,1,3,1,3,3,3,3,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,3,1,1,1,1,1,1,1,3,1,2,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,3,3,1,1,1,1,1,1,1,1,1,null,1,1,1,1,2,1,1,1,1,1,1,1,1,null,null,null,null,1,1,1,1,1,11,1,1,null,2,1,1,2,1,1,null,1,null,1,null,null,null,null,1,null,1,1,1,1,1,1,1,1,1,1,1,1,null,null,1,1,1,2,1,2,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,1,1,1,1,1,1,1,1,3,1,1,1,null,1,2,1,3,3,1,1,1,1,1,2,2,1,2,1,3,2,1,2,3,2,2,2,2,3,2,2,null,1,2,3,1,1,1,1,2,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,null,1,1,3,3,2,3,3,null,null,1,null,1,null,null,null,1,null,1,null,null,1,1,1,1,1,1,1,1,1,1,null,1,1,null,1,1,1,3,3,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,null,null,1,null,1,1,1,null,1,1,1,1,null,null,1,1,1,1,1,1,2,2,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,3,3,3,3,1,3,1,1,1,3,1,2,1,1,null,null,null,1,1,1,null,null,null,1,null,null,1,1,1,1,1,1,null,1,null,2,1,null,1,1,null,1,null,null,null,null,1,1,1,1,1,1,1,1,null,1,1,1,1,1,null,1,1,null,1,1,1,1,1,1,null,null,null,null,1,1,null,1,1,1,null,null,null,null,1,1,2,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,null,1,1,1,1,1,1,1,1,1,1,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,null,1,1,1,1,null,1,1,1,1,null,null,1,1,1,1,null,1,null,null,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,2,1,1,1,2,null,null,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,1,2,1,1,1,1,1,3,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,1,1,null,null,null,null,1,1,1,1,1,1,1,1,3,1,1,1,3,1,1,null,1,null,null,null,null,null,null,1,null,1,1,1,1,1,1,1,1,1,1,1,1,null,null,1,1,1,1,2,2,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,null,1,1,1,1,1,1,1,1,1,1,1,1,null,1,3,1,1,1,1,1,1,1,1,2,2,1,2,2,1,null,3,3,2,2,1,1,2,1,2,2,null,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1],[\"3\",\"3\",null,null,\"2\",\"2\",\"3\",\"3\",\"3\",\"3\",\"3\",null,null,\"3\",null,null,null,null,null,\"1\",null,\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,null,null,\"1\",\"2\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"2\",\"1\",\"1\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"3\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"3\",\"`\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"3\",\"3\",\"1\",\"3\",\"2\",\"1\",\"1\",\"3\",\"2\",\"1\",\"1\",\"1\",null,null,null,\"1\",\"1\",\"1\",null,null,null,\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"2\",\"2\",\"2\",\"1\",\"2\",null,\"1\",\"1\",null,\"1\",null,null,null,null,\"3\",\"1\",\"2\",\"2\",\"2\",\"1\",\"3\",\"1\",null,\"1\",\"3\",\"3\",\"3\",\"2\",null,\"2\",\"2\",null,\"1\",\"3\",\"2\",\"1\",\"2\",\"1\",null,null,null,null,\"1\",\"1\",null,null,null,null,null,null,null,null,\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",null,null,null,\"2\",null,null,null,\"2\",null,\"2\",null,null,null,\"2\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"2\",\"1\",\"3\",\"3\",\"3\",null,\"1\",\"3\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"2\",null,null,\"2\",null,\"3\",\"1\",\"1\",\"1\",null,\"3\",\"3\",\"3\",\"3\",null,null,\"1\",\"1\",\"1\",null,null,\"1\",null,null,\"3\",\"2\",\"3\",\"2\",\"1\",\"3\",\"1\",\"1\",null,null,\"3\",\"2\",\"3\",null,\"3\",\"3\",null,\"3\",\"2\",\"2\",\"2\",\"2\",\"3\",\"3\",\"3\",null,\"2\",\"1\",\"3\",\"3\",\"3\",\"3\",\"1\",null,null,\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"2\",\"1\",\"2\",\"2\",\"2\",\"2\",\"3\",\"2\",\"2\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"3\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"3\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"2\",null,\"3\",\"3\",null,\"2\",\"3\",\"1\",\"3\",\"3\",\"1\",\"3\",\"3\",\"2\",\"3\",\"3\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"2\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",null,\"1\",\"1\",\"1\",\"1\",\"3\",\"2\",\"3\",\"1\",\"1\",\"1\",\"3\",\"3\",\"1\",\"1\",\"2\",\"3\",\"3\",\"3\",\"1\",\"2\",\"2\",\"3\",\"1\",\"3\",\"3\",\"1\",\"3\",\"3\",\"3\",\"3\",\"2\",\"2\",\"2\",\"3\",\"3\",\"3\",\"2\",\"1\",\"1\",null,\"1\",\"1\",null,\"1\",null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"2\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",null,null,null,null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"3\",\"3\",\"2\",\"2\",\"2\",null,\"2\",null,\"1\",null,null,null,null,\"1\",null,\"3\",\"3\",\"2\",\"1\",\"1\",\"2\",\"1\",\"3\",\"2\",\"1\",\"1\",\"1\",null,null,null,\"3\",\"2\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",\"3\",\"1\",\"1\",\"1\",null,\"1\",\"3\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"3\",\"1\",\"3\",\"3\",null,\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"3\",\"2\",\"3\",\"1\",\"3\",\"2\",\"2\",\"3\",\"3\",\"2\",\"3\",\"2\",\"1\",\"3\",\"3\",\"3\",\"2\",\"2\",null,\"1\",\"1\",\"1\",\"3\",\"1\",\"3\",\"1\",\"3\",\"3\",\"1\",\"3\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"1\",\"2\",\"1\",\"1\",\"2\",\"1\"],[1,1,1,null,1,1,3,3,3,3,3,null,null,1,null,null,null,null,null,1,null,1,null,null,2,3,1,1,1,null,1,3,1,3,1,1,2,null,null,null,2,1,null,1,1,1,1,3,3,3,3,3,1,2,2,1,3,3,1,null,null,1,null,1,3,1,null,1,1,1,3,null,null,1,1,1,1,1,1,1,2,1,1,1,1,1,3,2,2,2,2,2,2,2,2,2,2,2,1,2,1,1,1,null,3,2,1,1,3,1,1,1,1,3,3,3,3,1,3,1,1,1,2,3,1,1,1,null,null,null,1,1,1,null,null,null,1,null,null,1,1,1,1,1,3,null,2,1,1,1,null,1,1,null,1,null,null,null,null,3,2,3,3,2,2,1,1,2,1,3,3,3,2,null,1,2,null,1,3,1,3,3,null,null,null,1,null,1,1,null,null,null,1,null,null,null,null,1,2,2,2,2,1,1,1,1,null,null,1,1,1,1,1,1,1,1,1,1,1,1,null,null,null,null,null,2,null,null,2,null,2,null,null,2,2,1,2,1,1,1,1,2,1,2,1,3,3,3,null,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,3,1,1,1,3,1,2,2,2,1,null,1,1,2,2,null,2,null,1,2,1,1,null,3,3,3,3,null,null,2,2,3,2,null,1,null,null,3,3,3,3,2,2,2,2,null,null,3,3,3,null,1,1,null,1,2,2,2,2,3,3,1,null,1,1,1,2,3,2,1,null,null,1,1,1,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,null,3,3,3,3,3,3,3,3,3,3,1,1,1,3,3,1,2,1,1,1,2,2,3,2,1,1,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,null,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,2,1,2,1,2,1,2,2,2,1,2,2,2,2,2,2,3,3,2,2,2,3,2,1,1,1,1,1,1,1,3,3,1,1,1,1,1,2,1,2,null,null,1,1,2,2,3,3,2,3,2,3,1,3,2,3,1,1,1,3,3,1,1,2,3,3,3,1,1,1,3,3,3,3,3,3,3,3,3,1,2,2,3,3,3,2,1,1,1,1,2,null,null,null,null,1,3,3,3,1,1,2,2,2,3,2,1,1,1,3,1,null,null,null,null,1,1,1,1,1,1,1,1,null,1,1,3,3,3,3,null,2,null,null,null,null,null,null,1,null,1,1,2,1,1,2,1,3,3,1,1,1,null,null,2,3,1,1,2,1,2,2,2,2,1,2,3,1,1,1,1,3,3,2,3,3,2,2,2,null,3,3,3,3,1,1,1,1,3,null,3,1,null,1,2,2,1,1,2,2,2,2,1,2,2,2,2,3,3,1,1,3,3,2,1,2,2,2,2,2,null,1,1,1,3,1,2,1,2,1,1,1,3,1,1,1,1,1,1,1,3,2,3,1,1,1,1],[\"Primary\",\"No formal\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"Higher\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"Primary\",\"Secondary\",\"Secondary\",\"Secondary\",\"Secondary\",\"Secondary\",\"No formal\",\"No formal\",\"Higher\",\"Secondary\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Primary\",\"Secondary\",\"Primary\",\"Secondary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"Secondary\",\"No formal\",\"Secondary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"No formal\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Higher\",\"Primary\",\"Secondary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"Secondary\",\"Secondary\",\"Secondary\",\"Secondary\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Higher\",\"Primary\",\"Secondary\",\"Primary\",\"No formal\",\"Primary\",\"No formal\",\"Secondary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"Higher\",\"No formal\",\"Secondary\",\"Secondary\",\"No formal\",\"No formal\",\"Higher\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Higher\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"Secondary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"Higher\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"Higher\",\"Secondary\",\"Secondary\",\"Secondary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Secondary\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"Primary\",\"Higher\",\"Secondary\",\"Primary\",\"Secondary\",\"No formal\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Primary\",\"Secondary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"Secondary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"Primary\",\"Secondary\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"Higher\",\"No formal\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",null,\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Secondary\",\"Secondary\",\"Secondary\",\"Secondary\",\"Primary\",\"No formal\",\"Primary\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",null,\"Secondary\",\"Secondary\",\"Secondary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Primary\",\"Secondary\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"Secondary\",\"Primary\",\"No formal\",\"Higher\",\"No formal\",\"Secondary\",\"No formal\",\"Higher\",\"Secondary\",\"No formal\",\"Secondary\",\"Primary\",\"Secondary\",\"No formal\",\"No formal\",\"Primary\",\"Higher\",\"Higher\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Secondary\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"Higher\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Higher\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",null,null,null,null,null,\"Secondary\",null,null,null,null,null,null,null,null,\"Primary\",\"Higher\",null,null,\"Secondary\",null,null,null,null,null,\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",\"Primary\",\"Primary\",\"No formal\",\"No formal\",\"Primary\",\"Higher\",\"No formal\",\"Primary\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"Secondary\",\"Secondary\",\"Primary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Primary\",null,\"No formal\",\"No formal\",\"No formal\",\"Primary\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"Secondary\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\",\"No formal\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>CPRO<\\/th>\\n      <th>CGEN<\\/th>\\n      <th>CRAC<\\/th>\\n      <th>CJOB<\\/th>\\n      <th>CQUI<\\/th>\\n      <th>TEIN<\\/th>\\n      <th>TAIN<\\/th>\\n      <th>TSII<\\/th>\\n      <th>TOIN<\\/th>\\n      <th>FEDU<\\/th>\\n      <th>FVTP<\\/th>\\n      <th>FCRA<\\/th>\\n      <th>FTAP<\\/th>\\n      <th>LHO1<\\/th>\\n      <th>LHO2<\\/th>\\n      <th>LHO3<\\/th>\\n      <th>LHO4<\\/th>\\n      <th>LCRE<\\/th>\\n      <th>LSAV<\\/th>\\n      <th>LWDA<\\/th>\\n      <th>PPO1<\\/th>\\n      <th>PPO2<\\/th>\\n      <th>PPO3<\\/th>\\n      <th>PPO4<\\/th>\\n      <th>PPO5<\\/th>\\n      <th>ARO1<\\/th>\\n      <th>ARO2<\\/th>\\n      <th>ARO3<\\/th>\\n      <th>ARO4<\\/th>\\n      <th>ARO5<\\/th>\\n      <th>FEDU_label<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":10,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[6,7,8,9,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"CPRO\",\"targets\":1},{\"name\":\"CGEN\",\"targets\":2},{\"name\":\"CRAC\",\"targets\":3},{\"name\":\"CJOB\",\"targets\":4},{\"name\":\"CQUI\",\"targets\":5},{\"name\":\"TEIN\",\"targets\":6},{\"name\":\"TAIN\",\"targets\":7},{\"name\":\"TSII\",\"targets\":8},{\"name\":\"TOIN\",\"targets\":9},{\"name\":\"FEDU\",\"targets\":10},{\"name\":\"FVTP\",\"targets\":11},{\"name\":\"FCRA\",\"targets\":12},{\"name\":\"FTAP\",\"targets\":13},{\"name\":\"LHO1\",\"targets\":14},{\"name\":\"LHO2\",\"targets\":15},{\"name\":\"LHO3\",\"targets\":16},{\"name\":\"LHO4\",\"targets\":17},{\"name\":\"LCRE\",\"targets\":18},{\"name\":\"LSAV\",\"targets\":19},{\"name\":\"LWDA\",\"targets\":20},{\"name\":\"PPO1\",\"targets\":21},{\"name\":\"PPO2\",\"targets\":22},{\"name\":\"PPO3\",\"targets\":23},{\"name\":\"PPO4\",\"targets\":24},{\"name\":\"PPO5\",\"targets\":25},{\"name\":\"ARO1\",\"targets\":26},{\"name\":\"ARO2\",\"targets\":27},{\"name\":\"ARO3\",\"targets\":28},{\"name\":\"ARO4\",\"targets\":29},{\"name\":\"ARO5\",\"targets\":30},{\"name\":\"FEDU_label\",\"targets\":31}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"orderCellsTop\":true}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n### Data preparation\n\nData are kept in tidy form; summary tables are built with **dplyr**.\n\nSummary by province:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby_province <- survey %>%\n  group_by(CPRO) %>%\n  summarise(\n    n = n(),\n    mean_income = mean(TEIN, na.rm = TRUE),\n    .groups = \"drop\"\n  )\nby_province\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  CPRO            n mean_income\n  <chr>       <int>       <dbl>\n1 Bac Giang     146        41.2\n2 Ha Giang      141        39.8\n3 Quang Ninh    144        38.3\n4 Tuyen Quang   150        37.6\n5 Yen Bai       143        33.0\n```\n\n\n:::\n:::\n\n\nSummary by race:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby_race <- survey %>%\n  count(CRAC, name = \"count\") %>%\n  mutate(pct = count / sum(count) * 100)\nby_race\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  CRAC            count   pct\n  <fct>           <int> <dbl>\n1 Kinh              336  46.4\n2 Ethnic minority   388  53.6\n```\n\n\n:::\n:::\n\n\nSummary by education level (with readable labels for plotting):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nby_edu <- survey %>%\n  filter(!is.na(FEDU_label)) %>%\n  group_by(FEDU_label, FEDU) %>%\n  summarise(\n    n = n(),\n    mean_tein = mean(TEIN, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  mutate(FEDU_label = fct_reorder(FEDU_label, mean_tein))\nby_edu\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  FEDU_label FEDU      n mean_tein\n  <fct>      <chr> <int>     <dbl>\n1 Higher     3        19     132. \n2 No formal  0       473      29.4\n3 Primary    1       136      43.0\n4 Secondary  2        73      60.1\n```\n\n\n:::\n:::\n\n\n## Working with Geometric objects\n\n### Histogram of total income (TEIN)\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- ggplot(data = survey, aes(x = TEIN)) +\n  geom_histogram(bins = 20, colour = \"grey25\", fill = \"grey85\") +\n  labs(title = \"Distribution of total income of informal rural labourers\",\n       x = \"Total income (Mil VND)\", y = \"Count\") +\n  theme_minimal()\np1\n```\n\n::: {.cell-output-display}\n![Distribution of total income (Mil VND)](TH_EX1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nThe histogram shows that total income (TEIN) in the sample is right-skewed. Most informal labourers have total income between about 20 and 50 million VND; the centre of the distribution lies in this range. The spread is wide, with a long right tail indicating a minority with much higher income. This pattern implies substantial inequality among rural informal workers in the northern mountainous regions: most earn modest amounts, while a smaller group earns considerably more, possibly reflecting different types of informal work or access to better opportunities.\n\n### Total income by gender (with statistical test)\n\nBoxplot with mean (red point); statistical evidence is provided by **ggstatsplot** (non-parametric Mann–Whitney test) so the conclusion is not based on visual overlap alone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np2 <- ggplot(data = survey, aes(y = TEIN, x = CGEN)) +\n  geom_boxplot(notch = TRUE, fill = \"grey92\") +\n  stat_summary(geom = \"point\", fun = \"mean\", colour = \"red\", size = 4) +\n  labs(x = \"Gender\", y = \"Total income (Mil VND)\", title = \"Total income by gender\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\np2\n```\n\n::: {.cell-output-display}\n![Total income by gender](TH_EX1_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(data = survey, x = CGEN, y = TEIN, type = \"np\",\n               title = \"Total income by gender\", xlab = \"Gender\", ylab = \"Total income (Mil VND)\")\n```\n\n::: {.cell-output-display}\n![Total income by gender — Mann-Whitney test](TH_EX1_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nThe test confirms that the difference in total income between males and females is not statistically significant (*p* shown in the plot). Medians and distributions are similar; the gender income gap among these informal rural labourers is small relative to variation within each group.\n\n### Plotting a bar chart\n\n[`geom_bar()`](https://ggplot2.tidyverse.org/reference/geom_bar.html) counts respondents by province; `coord_flip()` gives a horizontal bar chart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np3 <- ggplot(data = survey, aes(x = fct_infreq(CPRO))) +\n  geom_bar(fill = \"steelblue\", alpha = 0.85) +\n  coord_flip() +\n  labs(x = NULL, y = \"Count\", title = \"Number of respondents by province\") +\n  theme_minimal()\np3\n```\n\n::: {.cell-output-display}\n![Number of respondents by province](TH_EX1_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nRespondent counts are fairly balanced across the five provinces (Tuyen Quang, Quang Ninh, Ha Giang, Yen Bai, Bac Giang), with sample sizes around 141–150 per province. This balance supports comparisons of income and other outcomes by province.\n\n### Mean total income by education level\n\nPre-summarised data with [`geom_col()`](https://ggplot2.tidyverse.org/reference/geom_col.html); **viridis** (mako) encodes the gradient; bar-end labels avoid axis alignment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np4 <- ggplot(by_edu, aes(x = FEDU_label, y = mean_tein, fill = mean_tein)) +\n  geom_col(alpha = 0.9) +\n  geom_text(aes(label = round(mean_tein, 1)), hjust = -0.2, size = 3.2) +\n  coord_flip() +\n  scale_y_continuous(expand = expansion(mult = c(0, 0.12))) +\n  scale_fill_viridis_c(option = \"mako\", direction = -1) +\n  labs(\n    title = \"Education is the key income driver\",\n    subtitle = \"Higher education earners make ~4.5× more than those with no formal schooling\",\n    x = \"Education level\", y = \"Mean total income (Mil VND)\"\n  ) +\n  theme_minimal() +\n  theme(legend.position = \"none\")\np4\n```\n\n::: {.cell-output-display}\n![Mean total income by education level](TH_EX1_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nThere is a clear positive association between education level and mean total income. Mean income rises from about 29 Mil VND (no formal) to 43, 60, and about 132 Mil VND for primary, secondary, and higher education. The highest category earns substantially more, supporting the importance of education for income in this population and suggesting that policies aimed at schooling and training could improve outcomes for informal labourers in the northern mountainous regions.\n\n### Kernel density plot\n\nKernel density of total income by gender, with *colour* and *fill* in `aes()` for two groups.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np5 <- ggplot(data = survey, aes(x = TEIN, colour = CGEN, fill = CGEN)) +\n  geom_density(alpha = 0.3, linewidth = 0.8) +\n  labs(x = \"Total income (Mil VND)\", y = \"Density\", title = \"Total income distribution by gender\") +\n  theme_minimal()\np5\n```\n\n::: {.cell-output-display}\n![Density of total income by gender](TH_EX1_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nThe two density curves overlap heavily, with peaks in a similar range (roughly 25–45 Mil VND). Spread and shape are similar for both gender groups; there is no strong shift of one distribution relative to the other. The overlap indicates that the income distribution is largely similar for males and females in this sample. Any small differences in peak location or tail length are minor compared with the shared pattern of moderate centre and right-skewed spread.\n\n## Working with facets\n\n### Working with facet_wrap()\n\n[`facet_wrap()`](https://ggplot2.tidyverse.org/reference/facet_wrap.html) gives a trellis of total income by province.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np6 <- ggplot(data = survey, aes(x = TEIN)) +\n  geom_histogram(bins = 25, colour = \"grey25\", fill = \"steelblue\", alpha = 0.8) +\n  facet_wrap(~ CPRO, ncol = 2) +\n  labs(x = \"Total income (Mil VND)\", y = \"Count\", title = \"Total income distribution by province\") +\n  theme_minimal()\np6\n```\n\n::: {.cell-output-display}\n![Total income distribution by province](TH_EX1_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\nThe five panels show that income distribution shape and centre vary by province. Tuyen Quang, Quang Ninh, Ha Giang and Bac Giang have similar centres (mean income around 38–41 Mil VND), while **Yen Bai** has a lower centre (about 33 Mil VND). Yen Bai is a well-known mountainous province in northern Vietnam; its terrain may limit non-agricultural development and market access, which aligns with the lower income centre seen in the data. All panels are right-skewed, but spread and right-tail length differ. This regional heterogeneity—and the distinct position of Yen Bai—suggests that geography and local economic structure matter for informal labourers’ income and is a useful direction for further analysis or policy targeting in the northern mountainous regions.\n\n## Total income by credit accessibility\n\nBoxplot of total income by credit accessibility; statistical evidence from **ggstatsplot** (non-parametric test) to support policy-relevant conclusions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np7 <- ggplot(data = survey %>% filter(!is.na(FCRA)), aes(y = TEIN, x = FCRA)) +\n  geom_boxplot(notch = FALSE, fill = \"grey92\") +\n  stat_summary(geom = \"point\", fun = \"mean\", colour = \"red\", size = 4) +\n  labs(x = \"Credit accessibility\", y = \"Total income (Mil VND)\", title = \"Total income by credit accessibility\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\np7\n```\n\n::: {.cell-output-display}\n![Total income by credit accessibility](TH_EX1_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = survey %>% filter(!is.na(FCRA)),\n  x = FCRA, y = TEIN, type = \"np\",\n  title = \"Total income by credit accessibility\",\n  xlab = \"Credit accessibility\", ylab = \"Total income (Mil VND)\"\n)\n```\n\n::: {.cell-output-display}\n![Total income by credit accessibility — statistical test](TH_EX1_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nThe boxplots and test show how total income varies across credit accessibility (Low vs Medium). The *p*-value in the figure indicates whether the difference is statistically significant—relevant for policy: if easier credit access is associated with higher income, interventions to improve credit access may help informal labourers in the northern mountainous regions.\n\n## Total income by race\n\nThe sample includes a large share of ethnic minorities (by_race shows \\~54% in group 2). In northern mountainous Vietnam, race is a potential driver of income inequality. Below: boxplot and **ggstatsplot** for total income by race (Kinh vs Ethnic minority).\n\n\n::: {.cell}\n\n```{.r .cell-code}\np8 <- ggplot(data = survey %>% filter(!is.na(CRAC)), aes(y = TEIN, x = CRAC)) +\n  geom_boxplot(notch = TRUE, fill = \"grey92\") +\n  stat_summary(geom = \"point\", fun = \"mean\", colour = \"red\", size = 4) +\n  labs(x = \"Race\", y = \"Total income (Mil VND)\", title = \"Total income by race\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")\np8\n```\n\n::: {.cell-output-display}\n![Total income by race](TH_EX1_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggbetweenstats(\n  data = survey %>% filter(!is.na(CRAC)),\n  x = CRAC, y = TEIN, type = \"np\",\n  title = \"Total income by race\",\n  xlab = \"Race\", ylab = \"Total income (Mil VND)\"\n)\n```\n\n::: {.cell-output-display}\n![Total income by race — statistical test](TH_EX1_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nThe plot and test show whether total income differs significantly between Kinh and Ethnic minority labourers. In this region, ethnic minority status often correlates with remoteness and limited access to markets and services; a significant income gap would support targeted policies for inclusive development.\n\n## Composite figure (patchwork)\n\n[**patchwork**](https://patchwork.data-imaginist.com/) combines plots; `/` stacks them vertically. [`plot_annotation()`](https://patchwork.data-imaginist.com/reference/plot_annotation.html) with `tag_levels = 'I'` adds panel labels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 / p2 / p4 +\n  plot_annotation(\n    title = \"Income of informal rural labourers: distribution and by gender and education\",\n    tag_levels = \"I\"\n  )\n```\n\n::: {.cell-output-display}\n![Composite: income distribution, by gender, and by education](TH_EX1_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nPanel I shows the overall income distribution is right-skewed, with most labourers in the lower–middle income range. Panel II indicates that the gender gap in total income is small; medians and means are similar for both groups. Panel III shows a strong education–income gradient: mean income rises sharply with education level. Taken together, the main findings are: (1) income among these informal rural labourers is uneven and right-skewed; (2) gender differences in income are modest; and (3) education is a strong predictor of higher mean income, suggesting that policies supporting education may help improve outcomes in this population.\n\n## References\n\n-   Mai, A.N., Pham, T.H., Hoang, H.T., Nguyen, H.H.T. (2021). Income of informal labourers in rural areas: A survey dataset of northern mountainous regions in Vietnam. *Data in Brief* 38, 107292. <https://doi.org/10.1016/j.dib.2021.107292>\n-   Mendeley Data: <https://data.mendeley.com/datasets/s6p7dwj3j6/1>\n-   Creating enlightening and truthful data visualization. *Procedia Computer Science* (2021).\n-   Wickham et al., *ggplot2: Elegant Graphics for Data Analysis*. Springer.\n",
    "supporting": [
      "TH_EX1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/nouislider-7.0.10/jquery.nouislider.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/nouislider-7.0.10/jquery.nouislider.min.js\"></script>\n<link href=\"../../site_libs/selectize-0.12.0/selectize.bootstrap3.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/selectize-0.12.0/selectize.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}